<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Url;
use \Doctrine\ORM\EntityRepository;
use \DateTime;
/**
 * UrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlRepository extends EntityRepository
{
	/**
	 * Get info by short url
	 * @param string $short
	 *
	 * @return null|object
	 */
	public function getOneByShort(string $short)
	{
		return $this->findOneBy(['short' => $short]);
	}

	/**
	 * Return expired urls
	 * @return Url[]
	 */
	public function getExpiredUrls()
	{
		$expiredDate = new DateTime('-15 days');

		return $this->createQueryBuilder('url')
			->where('url.created <= :expireDate')
			->setParameter('expireDate', $expiredDate)
			->getQuery()
			->execute();
	}
}
