AppBundle\Entity\Url:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: original
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: short
    properties:
        original:
            - Length:
                min: 15
                max: 255
            - NotBlank: ~
            - NotNull: ~
            - AppBundle\Validator\Constraints\ValidUrl: ~
            - AppBundle\Validator\Constraints\ActiveUrl: ~
        short:
            - Length:
                min: 3
                max: 10
                minMessage: 'Short url must be at least {{ limit }} characters long'
                maxMessage: 'Short url cannot be longer than {{ limit }} characters'
            - AppBundle\Validator\Constraints\ContainsAlphanumeric: ~